### ISSUE TITLE
await PixivResult<PixivIllustration>.SearchAll(); throws error "PixeeSharp.PixivException: [ERROR] RequestCall() failed!"

### ISSUE THREAD

**Issue by DaOlHo** [jerwyk/PixeeSharp#2]
I'm trying to get all pixiv illustrations of a given user.

My code:
`PixivResult<PixivIllustration> illusts = await client.GetUserIllustrations(id);
            await illusts.SearchAll();`

Error:
``Exception thrown: 'PixeeSharp.PixivException' in mscorlib.dll
Exception thrown: 'PixeeSharp.PixivException' in mscorlib.dll
PixeeSharp.PixivException: [ERROR] RequestCall() failed!
   at PixeeSharp.PixeeSharpBaseApi.<GetStringRequest>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PixeeSharp.PixeeSharpAppApi.<GetStringRequest>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PixeeSharp.PixeeSharpAppApi.<GetUriResult>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at PixeeSharp.Models.PixivResult`1.<ReturnNextResult>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ImageArchiveApp.MainWindow.<PixivGalleryDownloadAsync>d__10.MoveNext() in C:\Users\dhodu\Dropbox\ImageArchiverApp\ImageArchiverApp\ImageArchiverApp.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ImageArchiveApp.MainWindow.<DownloadButton1_Click>d__2.MoveNext() in C:\Users\dhodu\Dropbox\ImageArchiverApp\ImageArchiverApp\ImageArchiverApp.cs:line 54``

I hope I'm not being annoying

**Comment by jerwyk** [comment]
There is a problem with how i handle deserialization for search results.. I will fix it ASAP once I have time hopefully. Also I really need a better error message system.

**Comment by jerwyk** [comment]
I have just updated nuget a fix for this issue, and hopefully now the major functions actually work properly. Also now you can see the actual error message returned by Pixiv so hopefully that helps.

**Comment by DaOlHo** [comment]
It works perfectly now, thank you
