### ISSUE TITLE
Login timer throws error and illust.Series is null

### ISSUE THREAD

**Issue by DaOlHo** [jerwyk/PixeeSharp#3]
Login timer error
`System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=PixeeSharp
  StackTrace:
   at PixeeSharp.PixeeSharpBaseApi.<RefreshTimer_Tick>d__23.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at ImageArchiverApp.Program.Main() in C:\Users\dhodu\Dropbox\ImageArchiverApp\ImageArchiverApp\Program.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]
    ImageArchiverApp.Program.Main() in Program.cs`

illust.Series just doesn't exist, just need it to sort files another way

**Comment by jerwyk** [comment]
Illust.Series will only not be null if the illustrations is in a series, which is actually pretty rare. Just note that series does not mean multiple images in one illustration. As for the login error, can you tell me which line triggers the error?

**Comment by jerwyk** [comment]
If you are sure that an image is in a series and it still returns null, just provide me with the illustration ID and I will test on that.

**Comment by DaOlHo** [comment]
By login timer I mean the periodic login that the api is supposed to perform. The error seems to just materialize from `Application.Run(new MainWindow());` in program.cs (generated by windows forms). As for the illust,series, I seem to have misinterpreted what it meant. My bad, sorry.

**Comment by jerwyk** [comment]
I havent fully figure out what is wrong with the login error, however I realized that windows form might have some issues with dispatch timer, which is supposed to be a WPF thing. I would suggest that you use `new PixeeSharpAppApi(null, null, null, -1);` to disable the dispatch timer, and create your own timer to periodically call the `api.Auth(api.RefreshToken);` method and see if it works.

**Comment by DaOlHo** [comment]
That seems to work, thank you. Sorry for the fuss.
